sonar.projectKey=hrm-api
sonar.projectName=HRM API
sonar.sources=src
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
